import type { ReactNode } from 'react';

/**
 * The frame both auth views share (design.md §49: extract a shared primitive
 * rather than duplicating visual logic).
 *
 * Two columns: on the left, what signing in to Atlas actually means; on the
 * right, the form. The claims on the left are the ones this system really
 * makes — a sign-in page is the first place someone decides whether a product
 * can be trusted with money, and the wrong move there is overstating.
 */
const POINTS = [
  {
    title: 'Passkey sign-in',
    body: 'WebAuthn on this device. No password to phish, nothing to write down.',
    icon: 'M4 8h16v11H4zM8 8V6a4 4 0 0 1 8 0v2',
  },
  {
    title: 'Your own threshold key',
    body: 'In threshold mode your deposit address is a 3-of-5 FROST group key. The console always shows which signing mode is running.',
    icon: 'M7 7h10v10H7zM12 2v5M12 17v5M2 12h5M17 12h5',
  },
  {
    title: 'Revocable sessions',
    body: 'Sessions are server-side and can be ended from any signed-in device.',
    icon: 'M12 3 4 6v6c0 4.4 3.4 8.2 8 9 4.6-.8 8-4.6 8-9V6l-8-3Z',
  },
] as const;

export function AuthPanel({
  title,
  description,
  children,
  footer,
}: {
  title: string;
  description: string;
  children: ReactNode;
  footer: ReactNode;
}) {
  return (
    <div className="grid min-h-[calc(100vh-140px)] items-center gap-12 py-12 lg:grid-cols-2 lg:gap-16">
      <div className="relative hidden lg:block">
        <div className="atlas-glow" aria-hidden="true" />
        <div className="relative max-w-[440px]">
          <h2 className="text-[32px] font-semibold leading-[1.15] tracking-[-0.02em] text-ink">
            Nothing to steal at sign-in. Nothing hidden after it.
          </h2>
          <p className="mt-4 leading-relaxed text-ink-secondary">
            Atlas is custody first: keys are generated by distributed key generation, and every
            movement of funds is double-entry accounted.
          </p>
          <div className="mt-7 flex flex-col gap-2.5">
            {POINTS.map((point) => (
              <div
                key={point.title}
                className="flex items-start gap-3 rounded-lg border border-line bg-background-subtle px-3.5 py-3"
              >
                <span className="grid h-[22px] w-[22px] shrink-0 place-items-center rounded-[5px] bg-accent-dim text-accent">
                  <svg
                    viewBox="0 0 24 24"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2.2"
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    className="h-3 w-3"
                    aria-hidden="true"
                  >
                    <path d={point.icon} />
                  </svg>
                </span>
                <div>
                  <p className="text-sm font-semibold text-ink">{point.title}</p>
                  <p className="mt-0.5 text-xs text-ink-muted">{point.body}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      <div className="flex justify-center">
        <div className="w-full max-w-[380px] animate-fade-up">
          <h1 className="text-[22px] font-semibold tracking-[-0.01em] text-ink">{title}</h1>
          <p className="mt-1.5 text-sm leading-relaxed text-ink-muted">{description}</p>
          <div className="mt-6">{children}</div>
          <div className="mt-6 text-center text-[12.5px] text-ink-muted">{footer}</div>
        </div>
      </div>
    </div>
  );
}
