-- Settlement (ADR-0034, prompt_phase_s4.md §§7-10).
--
-- 1. Tables — generated by `prisma migrate diff`, not hand-written.
-- 2. Grants, and append-only fills and tier snapshots.
-- 3. One `trade_settle` per fill, by constraint.
-- 4. The order machine gains `OPEN|PARTIALLY_FILLED -> CANCELLED` — GENERATED
--    from ORDER_TRANSITIONS; CI checks it (scripts/check-transition-constraints.mjs).
-- 5. The database refuses a negative trading balance (ADR-0034 §7).
-- 6. Structural constraints the type system cannot see past raw SQL.

-- ---------------------------------------------------------------------------
-- 1. Schema (prisma migrate diff)
-- ---------------------------------------------------------------------------
-- CreateTable
CREATE TABLE "fills" (
    "id" UUID NOT NULL,
    "fill_id" TEXT NOT NULL,
    "market" TEXT NOT NULL,
    "seq" BIGINT NOT NULL,
    "idx" INTEGER NOT NULL,
    "taker_order_id" UUID NOT NULL,
    "maker_order_id" UUID NOT NULL,
    "taker_user_id" UUID NOT NULL,
    "maker_user_id" UUID NOT NULL,
    "taker_side" "OrderSide" NOT NULL,
    "base_asset" TEXT NOT NULL,
    "quote_asset" TEXT NOT NULL,
    "price" DECIMAL(38,0) NOT NULL,
    "qty" DECIMAL(38,0) NOT NULL,
    "notional" DECIMAL(38,0) NOT NULL,
    "taker_fee_bps" INTEGER NOT NULL,
    "maker_fee_bps" INTEGER NOT NULL,
    "taker_fee" DECIMAL(38,0) NOT NULL,
    "maker_fee" DECIMAL(38,0) NOT NULL,
    "engine_timestamp" TIMESTAMPTZ(3) NOT NULL,
    "ledger_transaction_id" UUID NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "fills_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "engine_offsets" (
    "consumer" TEXT NOT NULL,
    "market" TEXT NOT NULL,
    "seq" BIGINT NOT NULL,
    "idx" INTEGER NOT NULL,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "engine_offsets_pkey" PRIMARY KEY ("consumer","market")
);

-- CreateTable
CREATE TABLE "fee_tier_snapshots" (
    "user_id" UUID NOT NULL,
    "quote_asset" TEXT NOT NULL,
    "day" DATE NOT NULL,
    "volume" DECIMAL(38,0) NOT NULL,
    "tier" INTEGER NOT NULL,
    "maker_bps" INTEGER NOT NULL,
    "taker_bps" INTEGER NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "fee_tier_snapshots_pkey" PRIMARY KEY ("user_id","quote_asset","day")
);

-- CreateIndex
CREATE UNIQUE INDEX "fills_fill_id_key" ON "fills"("fill_id");

-- CreateIndex
CREATE UNIQUE INDEX "fills_ledger_transaction_id_key" ON "fills"("ledger_transaction_id");

-- CreateIndex
CREATE INDEX "fills_taker_order_id_idx" ON "fills"("taker_order_id");

-- CreateIndex
CREATE INDEX "fills_maker_order_id_idx" ON "fills"("maker_order_id");

-- CreateIndex
CREATE INDEX "fills_taker_user_id_quote_asset_engine_timestamp_idx" ON "fills"("taker_user_id", "quote_asset", "engine_timestamp");

-- CreateIndex
CREATE INDEX "fills_maker_user_id_quote_asset_engine_timestamp_idx" ON "fills"("maker_user_id", "quote_asset", "engine_timestamp");

-- CreateIndex
CREATE UNIQUE INDEX "fills_market_seq_idx_key" ON "fills"("market", "seq", "idx");

-- A fill names its settlement before the settlement exists: the fill row is
-- inserted first, ON CONFLICT DO NOTHING, and the ledger transaction is posted
-- only if that insert won. DEFERRED, therefore, exactly as an order names its
-- hold — and a fill committed without its settlement is refused outright.
ALTER TABLE "fills" ADD CONSTRAINT "fills_ledger_transaction_fkey"
  FOREIGN KEY ("ledger_transaction_id") REFERENCES "ledger_transactions"("id")
  ON DELETE NO ACTION ON UPDATE NO ACTION
  DEFERRABLE INITIALLY DEFERRED;

-- ---------------------------------------------------------------------------
-- 2. Grants.
--
-- A fill and a tier snapshot are evidence: what was charged, and why. Neither
-- is ever edited. The offset is the one row settlement updates in place.
-- ---------------------------------------------------------------------------
GRANT SELECT, INSERT         ON TABLE "fills"              TO wallet_app;
GRANT SELECT, INSERT         ON TABLE "fee_tier_snapshots" TO wallet_app;
GRANT SELECT, INSERT, UPDATE ON TABLE "engine_offsets"     TO wallet_app;
REVOKE UPDATE, DELETE, TRUNCATE ON TABLE "fills"              FROM wallet_app;
REVOKE UPDATE, DELETE, TRUNCATE ON TABLE "fee_tier_snapshots" FROM wallet_app;
REVOKE DELETE, TRUNCATE         ON TABLE "engine_offsets"     FROM wallet_app;

CREATE OR REPLACE FUNCTION settlement_record_is_append_only()
RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION
    '% is append-only: % is not permitted. It records what a settlement charged and why.',
    TG_TABLE_NAME, TG_OP
    USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS fills_no_update ON "fills";
CREATE TRIGGER fills_no_update BEFORE UPDATE ON "fills"
  FOR EACH ROW EXECUTE FUNCTION settlement_record_is_append_only();
DROP TRIGGER IF EXISTS fills_no_delete ON "fills";
CREATE TRIGGER fills_no_delete BEFORE DELETE ON "fills"
  FOR EACH ROW EXECUTE FUNCTION settlement_record_is_append_only();
DROP TRIGGER IF EXISTS fee_tier_snapshots_no_update ON "fee_tier_snapshots";
CREATE TRIGGER fee_tier_snapshots_no_update BEFORE UPDATE ON "fee_tier_snapshots"
  FOR EACH ROW EXECUTE FUNCTION settlement_record_is_append_only();
DROP TRIGGER IF EXISTS fee_tier_snapshots_no_delete ON "fee_tier_snapshots";
CREATE TRIGGER fee_tier_snapshots_no_delete BEFORE DELETE ON "fee_tier_snapshots"
  FOR EACH ROW EXECUTE FUNCTION settlement_record_is_append_only();

-- ---------------------------------------------------------------------------
-- 3. A fill is settled EXACTLY ONCE (ADR-0034 §4).
--
-- PARTIAL, never global: one withdrawal already produces several ledger
-- transactions sharing (reference_type, reference_id). `fills.fill_id` is
-- unique as well; this index is the ledger's own copy of the guarantee, so a
-- second `trade_settle` for one fill is refused even by a path that skipped
-- the fills table.
-- ---------------------------------------------------------------------------
CREATE UNIQUE INDEX IF NOT EXISTS ledger_transactions_trade_fill_uniq
  ON ledger_transactions (reference_id) WHERE kind = 'trade_settle';

-- ---------------------------------------------------------------------------
-- 4. Legal order transitions.
-- ---------------------------------------------------------------------------
-- BEGIN GENERATED by packages/db/scripts/check-transition-constraints.mjs --emit order
-- Source: ORDER_TRANSITIONS in packages/types/src/order-states.ts. Do not edit by hand;
-- CI compares this list against the TypeScript table.
CREATE OR REPLACE FUNCTION order_transition_is_legal()
RETURNS TRIGGER AS $$
DECLARE
  legal BOOLEAN;
BEGIN
  IF NEW.from_status IS NULL THEN
    RETURN NEW;
  END IF;

  SELECT EXISTS (
    SELECT 1 FROM (VALUES
    ('PENDING_ENGINE', 'OPEN'),
    ('PENDING_ENGINE', 'PARTIALLY_FILLED'),
    ('PENDING_ENGINE', 'FILLED'),
    ('PENDING_ENGINE', 'REJECTED'),
    ('PENDING_ENGINE', 'EXPIRED'),
    ('PENDING_ENGINE', 'FAILED'),
    ('OPEN', 'PARTIALLY_FILLED'),
    ('OPEN', 'FILLED'),
    ('OPEN', 'PENDING_CANCEL'),
    ('OPEN', 'CANCELLED'),
    ('OPEN', 'EXPIRED'),
    ('PARTIALLY_FILLED', 'FILLED'),
    ('PARTIALLY_FILLED', 'PENDING_CANCEL'),
    ('PARTIALLY_FILLED', 'CANCELLED'),
    ('PARTIALLY_FILLED', 'EXPIRED'),
    ('PENDING_CANCEL', 'CANCELLED'),
    ('PENDING_CANCEL', 'FILLED'),
    ('PENDING_CANCEL', 'PARTIALLY_FILLED')
    ) AS t(from_status, to_status)
    WHERE t.from_status = NEW.from_status::text
      AND t.to_status   = NEW.to_status::text
  ) INTO legal;

  IF NOT legal THEN
    RAISE EXCEPTION 'illegal order transition % -> %', NEW.from_status, NEW.to_status
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
-- END GENERATED

-- ---------------------------------------------------------------------------
-- 5. No user trading balance may go negative (ADR-0034 §7).
--
-- Until S4 the only sufficient-funds check was the SERIALIZABLE read-then-post
-- that takes a hold. S4 is the first phase where a COMPUTATION — fees, fill
-- prices, the outstanding hold — decides how much is debited from a hold, and
-- a bug there would balance perfectly and commit a negative balance. This turns
-- that bug into a refused commit.
--
-- DEFERRED, so it sees the transaction's final state: a hold posted and
-- consumed in one transaction is judged on where it ends, not on the order its
-- entries were inserted in. Only a DEBIT can reduce a liability balance, so
-- only debits are checked. Custody-tier accounts are out of scope here.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION ledger_trading_balance_non_negative()
RETURNS TRIGGER AS $$
DECLARE
  account RECORD;
  balance NUMERIC;
BEGIN
  IF NEW.direction <> 'debit' THEN
    RETURN NULL;
  END IF;

  SELECT type, owner_id INTO account FROM "ledger_accounts" WHERE id = NEW.account_id;
  IF account.owner_id IS NULL
     OR account.type NOT IN ('user_trading_available', 'user_order_locked', 'user_trading_locked') THEN
    RETURN NULL;
  END IF;

  SELECT COALESCE(SUM(CASE WHEN direction = 'credit' THEN amount ELSE -amount END), 0)
    INTO balance
    FROM "ledger_entries"
   WHERE account_id = NEW.account_id;

  IF balance < 0 THEN
    -- The account id only: no owner, no amount (prompt_phase_s4.md rule 106).
    RAISE EXCEPTION
      'ledger transaction % would leave trading account % (%) negative (ADR-0034 §7)',
      NEW.transaction_id, NEW.account_id, account.type
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS ledger_entries_trading_non_negative ON "ledger_entries";
CREATE CONSTRAINT TRIGGER ledger_entries_trading_non_negative
  AFTER INSERT ON "ledger_entries"
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION ledger_trading_balance_non_negative();

-- ---------------------------------------------------------------------------
-- 6. Structural constraints.
-- ---------------------------------------------------------------------------
ALTER TABLE "fills" ADD CONSTRAINT fills_seq_positive     CHECK (seq > 0);
ALTER TABLE "fills" ADD CONSTRAINT fills_idx_non_negative CHECK (idx >= 0);
ALTER TABLE "fills" ADD CONSTRAINT fills_price_positive   CHECK (price > 0);
ALTER TABLE "fills" ADD CONSTRAINT fills_qty_positive     CHECK (qty > 0);
ALTER TABLE "fills" ADD CONSTRAINT fills_amounts_non_negative
  CHECK (notional >= 0 AND taker_fee >= 0 AND maker_fee >= 0);
ALTER TABLE "fills" ADD CONSTRAINT fills_fee_bps_bounded
  CHECK (taker_fee_bps BETWEEN 0 AND 10000 AND maker_fee_bps BETWEEN 0 AND 10000);
-- A fee is a fraction of the notional; either side's above it is arithmetic gone wrong.
ALTER TABLE "fills" ADD CONSTRAINT fills_fees_within_notional
  CHECK (taker_fee <= notional AND maker_fee <= notional);
-- The engine never matches an order against itself.
ALTER TABLE "fills" ADD CONSTRAINT fills_distinct_orders CHECK (taker_order_id <> maker_order_id);
ALTER TABLE "fills" ADD CONSTRAINT fills_assets_cluster CHECK (
  ledger_asset_cluster(base_asset) IS NOT NULL AND
  ledger_asset_cluster(quote_asset) IS NOT NULL AND
  base_asset <> quote_asset
);

ALTER TABLE "engine_offsets" ADD CONSTRAINT engine_offsets_position_non_negative
  CHECK (seq >= 0 AND idx >= 0);

ALTER TABLE "fee_tier_snapshots" ADD CONSTRAINT fee_tier_snapshots_values_non_negative
  CHECK (volume >= 0 AND tier >= 0 AND maker_bps >= 0 AND taker_bps >= 0);
