// GENERATED by packages/db/scripts/generate-account-types.mjs — do not edit.
//
// The source is ACCOUNT_TYPES in packages/ledger/src/accounts.ts. Run
// `pnpm --filter @wallet/db generate:account-types` after changing it; CI
// fails on drift.
//
// `packages/db` does not import `@wallet/ledger` at runtime — the ledger is a
// pure domain package and this is its persistence layer, so the dependency is
// generated rather than taken.

export const LEDGER_ACCOUNT_TYPES = [
  'user_custody_available',
  'user_custody_locked',
  'user_trading_available',
  'user_order_locked',
  'clearing_assets',
  'house_trading_fees',
  'chain_assets',
  'house_fees',
  'house_rent',
  'external',
] as const;

export type LedgerAccountType = (typeof LEDGER_ACCOUNT_TYPES)[number];

// Source: TRANSACTION_KINDS in packages/ledger/src/entries.ts. The same
// four-copy problem as account types, fixed the same way.
export const LEDGER_TRANSACTION_KINDS = [
  'deposit',
  'withdrawal_lock',
  'withdrawal_release',
  'withdrawal_settle',
  'sweep',
  'fee',
  'allocation',
  'deallocation',
  'order_hold',
  'order_release',
  'adjustment',
] as const;

export type LedgerTransactionKind = (typeof LEDGER_TRANSACTION_KINDS)[number];
