-- Pre-trade risk decisions (ADR-0033). Tables generated by prisma migrate diff.

-- CreateTable
CREATE TABLE "order_risk_decisions" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "client_order_id" TEXT NOT NULL,
    "market" TEXT NOT NULL,
    "verdict" "RiskVerdict" NOT NULL,
    "codes" TEXT[],
    "evaluated_rules" TEXT[],
    "input_snapshot" JSONB NOT NULL,
    "outcomes" JSONB NOT NULL,
    "policy_version" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "order_risk_decisions_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "order_risk_decisions_user_id_created_at_idx" ON "order_risk_decisions"("user_id", "created_at");


-- Append-only, for both the application role and the schema owner — the same
-- mechanism as risk_decisions. A decision is evidence of why an order was or
-- was not allowed, and evidence is not edited.
GRANT SELECT, INSERT ON TABLE "order_risk_decisions" TO wallet_app;
REVOKE UPDATE, DELETE, TRUNCATE ON TABLE "order_risk_decisions" FROM wallet_app;

DROP TRIGGER IF EXISTS order_risk_decisions_no_update ON "order_risk_decisions";
CREATE TRIGGER order_risk_decisions_no_update
  BEFORE UPDATE ON "order_risk_decisions"
  FOR EACH ROW EXECUTE FUNCTION order_history_is_append_only();

DROP TRIGGER IF EXISTS order_risk_decisions_no_delete ON "order_risk_decisions";
CREATE TRIGGER order_risk_decisions_no_delete
  BEFORE DELETE ON "order_risk_decisions"
  FOR EACH ROW EXECUTE FUNCTION order_history_is_append_only();
