-- Market data (ADR-0036, prompt_phase_s5.md §§6-7).
--
-- 1. Tables — generated by `prisma migrate diff`, not hand-written.
-- 2. Grants. The tape is append-only; candles are derived and mutable.
-- 3. Structural constraints.

-- ---------------------------------------------------------------------------
-- 1. Schema (prisma migrate diff)
-- ---------------------------------------------------------------------------
-- CreateTable
CREATE TABLE "trades" (
    "market" TEXT NOT NULL,
    "seq" BIGINT NOT NULL,
    "fill_index" INTEGER NOT NULL,
    "price" DECIMAL(38,0) NOT NULL,
    "qty" DECIMAL(38,0) NOT NULL,
    "quote_qty" DECIMAL(38,0) NOT NULL,
    "taker_side" "OrderSide" NOT NULL,
    "engine_timestamp" TIMESTAMPTZ(3) NOT NULL,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "trades_pkey" PRIMARY KEY ("market","seq","fill_index")
);

-- CreateTable
CREATE TABLE "candles" (
    "market" TEXT NOT NULL,
    "bucket_start" TIMESTAMPTZ(3) NOT NULL,
    "open" DECIMAL(38,0) NOT NULL,
    "high" DECIMAL(38,0) NOT NULL,
    "low" DECIMAL(38,0) NOT NULL,
    "close" DECIMAL(38,0) NOT NULL,
    "open_seq" BIGINT NOT NULL,
    "open_index" INTEGER NOT NULL,
    "close_seq" BIGINT NOT NULL,
    "close_index" INTEGER NOT NULL,
    "base_volume" DECIMAL(38,0) NOT NULL,
    "quote_volume" DECIMAL(38,0) NOT NULL,
    "trade_count" INTEGER NOT NULL,

    CONSTRAINT "candles_pkey" PRIMARY KEY ("market","bucket_start")
);

-- CreateIndex
CREATE INDEX "trades_market_engine_timestamp_idx" ON "trades"("market", "engine_timestamp");

-- ---------------------------------------------------------------------------
-- 2. Grants.
--
-- A trade is a public record of what matched: never edited. A candle is a
-- cache of an aggregate over trades: recomputed in place, and deleted and
-- rebuilt by the rebuild command.
-- ---------------------------------------------------------------------------
GRANT SELECT, INSERT                 ON TABLE "trades"  TO wallet_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE "candles" TO wallet_app;
REVOKE UPDATE, DELETE, TRUNCATE ON TABLE "trades"  FROM wallet_app;
REVOKE TRUNCATE                 ON TABLE "candles" FROM wallet_app;

CREATE OR REPLACE FUNCTION trades_are_append_only()
RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION
    'trades is append-only: % is not permitted. It records what the engine matched.', TG_OP
    USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trades_no_update ON "trades";
CREATE TRIGGER trades_no_update BEFORE UPDATE ON "trades"
  FOR EACH ROW EXECUTE FUNCTION trades_are_append_only();
DROP TRIGGER IF EXISTS trades_no_delete ON "trades";
CREATE TRIGGER trades_no_delete BEFORE DELETE ON "trades"
  FOR EACH ROW EXECUTE FUNCTION trades_are_append_only();

-- ---------------------------------------------------------------------------
-- 3. Structural constraints.
-- ---------------------------------------------------------------------------
ALTER TABLE "trades" ADD CONSTRAINT trades_seq_positive        CHECK (seq > 0);
ALTER TABLE "trades" ADD CONSTRAINT trades_index_non_negative  CHECK (fill_index >= 0);
ALTER TABLE "trades" ADD CONSTRAINT trades_price_positive      CHECK (price > 0);
ALTER TABLE "trades" ADD CONSTRAINT trades_qty_positive        CHECK (qty > 0);
ALTER TABLE "trades" ADD CONSTRAINT trades_quote_non_negative  CHECK (quote_qty >= 0);

ALTER TABLE "candles" ADD CONSTRAINT candles_prices_ordered
  CHECK (low > 0 AND low <= open AND low <= close AND high >= open AND high >= close);
ALTER TABLE "candles" ADD CONSTRAINT candles_has_trades CHECK (trade_count > 0);
ALTER TABLE "candles" ADD CONSTRAINT candles_volumes_non_negative
  CHECK (base_volume > 0 AND quote_volume >= 0);
-- A bucket starts on a UTC minute, or two rows could describe one minute.
ALTER TABLE "candles" ADD CONSTRAINT candles_bucket_on_the_minute
  CHECK (bucket_start = date_bin('1 minute', bucket_start, TIMESTAMPTZ '1970-01-01 00:00:00+00'));
