-- The order gateway (ADR-0025, prompt_phase_s3.md §§7, 10, 11).
--
-- 1. Tables and enums — generated by `prisma migrate diff`, not hand-written.
-- 2. Grants and append-only triggers for the order history.
-- 3. The legal-transition trigger — GENERATED from ORDER_TRANSITIONS in
--    packages/types/src/order-states.ts. CI checks the VALUES list below
--    against that table (scripts/check-transition-constraints.mjs).
-- 4. Structural constraints the type system cannot see past raw SQL.

-- ---------------------------------------------------------------------------
-- 1. Schema (prisma migrate diff)
-- ---------------------------------------------------------------------------
-- CreateEnum
CREATE TYPE "WithdrawalPurpose" AS ENUM ('external', 'allocation', 'deallocation');

-- CreateEnum
CREATE TYPE "OrderStatus" AS ENUM ('PENDING_ENGINE', 'OPEN', 'PARTIALLY_FILLED', 'PENDING_CANCEL', 'FILLED', 'CANCELLED', 'REJECTED', 'EXPIRED', 'FAILED');

-- CreateEnum
CREATE TYPE "OrderSide" AS ENUM ('buy', 'sell');

-- CreateEnum
CREATE TYPE "OrderKind" AS ENUM ('limit', 'market');

-- CreateEnum
CREATE TYPE "OrderTimeInForce" AS ENUM ('GTC', 'IOC', 'FOK');

-- AlterTable
ALTER TABLE "withdrawals" ADD COLUMN     "purpose" "WithdrawalPurpose" NOT NULL DEFAULT 'external';

-- CreateTable
CREATE TABLE "orders" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "client_order_id" TEXT NOT NULL,
    "market" TEXT NOT NULL,
    "side" "OrderSide" NOT NULL,
    "kind" "OrderKind" NOT NULL,
    "time_in_force" "OrderTimeInForce" NOT NULL,
    "post_only" BOOLEAN NOT NULL,
    "price" DECIMAL(38,0),
    "qty" DECIMAL(38,0) NOT NULL,
    "filled_qty" DECIMAL(38,0) NOT NULL DEFAULT 0,
    "status" "OrderStatus" NOT NULL DEFAULT 'PENDING_ENGINE',
    "hold_asset" TEXT NOT NULL,
    "hold_amount" DECIMAL(38,0) NOT NULL,
    "hold_ledger_transaction_id" UUID NOT NULL,
    "engine_seq" BIGINT,
    "reject_reason" TEXT,
    "sweep_attempts" INTEGER NOT NULL DEFAULT 0,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(3) NOT NULL,

    CONSTRAINT "orders_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "order_transitions" (
    "id" UUID NOT NULL,
    "order_id" UUID NOT NULL,
    "from_status" "OrderStatus",
    "to_status" "OrderStatus" NOT NULL,
    "reason" TEXT,
    "correlation_id" TEXT,
    "created_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "order_transitions_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "orders_status_created_at_idx" ON "orders"("status", "created_at");

-- CreateIndex
CREATE INDEX "orders_user_id_market_status_idx" ON "orders"("user_id", "market", "status");

-- CreateIndex
CREATE UNIQUE INDEX "orders_user_id_client_order_id_key" ON "orders"("user_id", "client_order_id");

-- CreateIndex
CREATE INDEX "order_transitions_order_id_created_at_idx" ON "order_transitions"("order_id", "created_at");

-- AddForeignKey
ALTER TABLE "orders" ADD CONSTRAINT "orders_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "order_transitions" ADD CONSTRAINT "order_transitions_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE CASCADE;


-- ---------------------------------------------------------------------------
-- 2. Grants, and an append-only order history.
--
-- The same mechanism as ledger_entries and withdrawal_transitions: the grant
-- removes the verbs from the application role, and the triggers stop the
-- schema owner too.
-- ---------------------------------------------------------------------------
GRANT SELECT, INSERT, UPDATE ON TABLE "orders"            TO wallet_app;
GRANT SELECT, INSERT         ON TABLE "order_transitions" TO wallet_app;
REVOKE UPDATE, DELETE, TRUNCATE ON TABLE "order_transitions" FROM wallet_app;
-- An order is never deleted: it is evidence of a hold that was posted.
REVOKE DELETE, TRUNCATE ON TABLE "orders" FROM wallet_app;

CREATE OR REPLACE FUNCTION order_history_is_append_only()
RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION
    '% is append-only: % is not permitted. An order''s history is evidence of what happened to a hold.',
    TG_TABLE_NAME, TG_OP
    USING ERRCODE = 'restrict_violation';
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS order_transitions_no_update ON "order_transitions";
CREATE TRIGGER order_transitions_no_update
  BEFORE UPDATE ON "order_transitions"
  FOR EACH ROW EXECUTE FUNCTION order_history_is_append_only();

DROP TRIGGER IF EXISTS order_transitions_no_delete ON "order_transitions";
CREATE TRIGGER order_transitions_no_delete
  BEFORE DELETE ON "order_transitions"
  FOR EACH ROW EXECUTE FUNCTION order_history_is_append_only();

-- ---------------------------------------------------------------------------
-- 3. Only legal transitions may be recorded.
-- ---------------------------------------------------------------------------
-- BEGIN GENERATED by packages/db/scripts/check-transition-constraints.mjs --emit order
-- Source: ORDER_TRANSITIONS in packages/types/src/order-states.ts. Do not edit by hand;
-- CI compares this list against the TypeScript table.
CREATE OR REPLACE FUNCTION order_transition_is_legal()
RETURNS TRIGGER AS $$
DECLARE
  legal BOOLEAN;
BEGIN
  IF NEW.from_status IS NULL THEN
    RETURN NEW;
  END IF;

  SELECT EXISTS (
    SELECT 1 FROM (VALUES
    ('PENDING_ENGINE', 'OPEN'),
    ('PENDING_ENGINE', 'PARTIALLY_FILLED'),
    ('PENDING_ENGINE', 'FILLED'),
    ('PENDING_ENGINE', 'REJECTED'),
    ('PENDING_ENGINE', 'EXPIRED'),
    ('PENDING_ENGINE', 'FAILED'),
    ('OPEN', 'PARTIALLY_FILLED'),
    ('OPEN', 'FILLED'),
    ('OPEN', 'PENDING_CANCEL'),
    ('OPEN', 'EXPIRED'),
    ('PARTIALLY_FILLED', 'FILLED'),
    ('PARTIALLY_FILLED', 'PENDING_CANCEL'),
    ('PARTIALLY_FILLED', 'EXPIRED'),
    ('PENDING_CANCEL', 'CANCELLED'),
    ('PENDING_CANCEL', 'FILLED'),
    ('PENDING_CANCEL', 'PARTIALLY_FILLED')
    ) AS t(from_status, to_status)
    WHERE t.from_status = NEW.from_status::text
      AND t.to_status   = NEW.to_status::text
  ) INTO legal;

  IF NOT legal THEN
    RAISE EXCEPTION 'illegal order transition % -> %', NEW.from_status, NEW.to_status
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
-- END GENERATED

DROP TRIGGER IF EXISTS order_transitions_legal ON "order_transitions";
CREATE TRIGGER order_transitions_legal
  BEFORE INSERT ON "order_transitions"
  FOR EACH ROW EXECUTE FUNCTION order_transition_is_legal();

-- ---------------------------------------------------------------------------
-- 4. Structural constraints.
-- ---------------------------------------------------------------------------

-- AN ORDER CANNOT EXIST WITHOUT ITS HOLD.
--
-- The gateway inserts the order row first (ON CONFLICT DO NOTHING, so a repeated
-- clientOrderId never posts a second hold) and posts the hold only if that
-- insert won — so the ledger transaction does not exist yet when the order row
-- is written. DEFERRED, therefore: checked at COMMIT (or at the explicit
-- `SET CONSTRAINTS ALL IMMEDIATE` withTransaction issues), by which point the
-- hold must be there. An order committed without one is refused outright.
ALTER TABLE "orders" ADD CONSTRAINT orders_hold_ledger_transaction_fkey
  FOREIGN KEY (hold_ledger_transaction_id) REFERENCES ledger_transactions(id)
  DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "orders" ADD CONSTRAINT orders_qty_positive  CHECK (qty > 0);
ALTER TABLE "orders" ADD CONSTRAINT orders_hold_positive CHECK (hold_amount > 0);
ALTER TABLE "orders" ADD CONSTRAINT orders_filled_bounded
  CHECK (filled_qty >= 0 AND filled_qty <= qty);
ALTER TABLE "orders" ADD CONSTRAINT orders_sweep_attempts_non_negative
  CHECK (sweep_attempts >= 0);
-- A limit order carries a price; a market order must not (packages/orders).
ALTER TABLE "orders" ADD CONSTRAINT orders_price_matches_kind CHECK (
  (kind = 'limit'  AND price IS NOT NULL AND price > 0) OR
  (kind = 'market' AND price IS NULL)
);
-- A ledger asset key is always cluster-qualified (ADR-0021).
ALTER TABLE "orders" ADD CONSTRAINT orders_hold_asset_cluster
  CHECK (ledger_asset_cluster(hold_asset) IS NOT NULL);

-- An allocation's destination is configuration, never a client parameter
-- (prompt_phase_s3.md rule 74). The database cannot know the configured
-- address, but it can refuse the one shape that is certainly wrong: an
-- internal movement with no destination at all.
ALTER TABLE "withdrawals" ADD CONSTRAINT withdrawals_internal_has_destination
  CHECK (purpose = 'external' OR length(destination) > 0);
