-- PENDING_CANCEL -> EXPIRED becomes a legal order transition (ADR-0034 §6,
-- amended by prompt_phase_s5.md §16).
--
-- An IOC that fills in part expires its remainder in the SAME engine command.
-- Until settlement applies that command the gateway shows the order OPEN, and
-- its owner — or a cancel-all — can cancel it. The cancel finds nothing in the
-- book, the engine answers Rejected{UnknownOrder}, and the order is left
-- PENDING_CANCEL. Settlement then reaches the command: the fill is recorded,
-- and the `Expired` that follows had no legal transition to make. It halted
-- the market. An `Expired` is a fact about the book, exactly as `Cancelled`
-- is (the 2026-10-01 migration made the same correction for that event).
--
-- GENERATED from ORDER_TRANSITIONS; CI checks it
-- (scripts/check-transition-constraints.mjs).

-- BEGIN GENERATED by packages/db/scripts/check-transition-constraints.mjs --emit order
-- Source: ORDER_TRANSITIONS in packages/types/src/order-states.ts. Do not edit by hand;
-- CI compares this list against the TypeScript table.
CREATE OR REPLACE FUNCTION order_transition_is_legal()
RETURNS TRIGGER AS $$
DECLARE
  legal BOOLEAN;
BEGIN
  IF NEW.from_status IS NULL THEN
    RETURN NEW;
  END IF;

  SELECT EXISTS (
    SELECT 1 FROM (VALUES
    ('PENDING_ENGINE', 'OPEN'),
    ('PENDING_ENGINE', 'PARTIALLY_FILLED'),
    ('PENDING_ENGINE', 'FILLED'),
    ('PENDING_ENGINE', 'REJECTED'),
    ('PENDING_ENGINE', 'EXPIRED'),
    ('PENDING_ENGINE', 'FAILED'),
    ('OPEN', 'PARTIALLY_FILLED'),
    ('OPEN', 'FILLED'),
    ('OPEN', 'PENDING_CANCEL'),
    ('OPEN', 'CANCELLED'),
    ('OPEN', 'EXPIRED'),
    ('PARTIALLY_FILLED', 'FILLED'),
    ('PARTIALLY_FILLED', 'PENDING_CANCEL'),
    ('PARTIALLY_FILLED', 'CANCELLED'),
    ('PARTIALLY_FILLED', 'EXPIRED'),
    ('PENDING_CANCEL', 'CANCELLED'),
    ('PENDING_CANCEL', 'FILLED'),
    ('PENDING_CANCEL', 'PARTIALLY_FILLED'),
    ('PENDING_CANCEL', 'EXPIRED')
    ) AS t(from_status, to_status)
    WHERE t.from_status = NEW.from_status::text
      AND t.to_status   = NEW.to_status::text
  ) INTO legal;

  IF NOT legal THEN
    RAISE EXCEPTION 'illegal order transition % -> %', NEW.from_status, NEW.to_status
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;
-- END GENERATED
